
t2m_path: deps/t2m/
t2m_textencoder:
  target: hGPT.models.evaluator.TextEncoderBiGRUCo
  params:
    word_size: 300
    pos_size: 15
    hidden_size: 512
    output_size: 512
t2m_moveencoder:
  target: hGPT.models.evaluator.MovementConvEncoder
  params:
    input_size: ${eval:${DATASET.NFEATS} - 4}
    hidden_size: 512
    output_size: 512
t2m_motionencoder:
  target: hGPT.models.evaluator.MotionEncoderBiGRUCo
  params:
    input_size: ${eval.tm2t_x.t2m_moveencoder.params.output_size}
    hidden_size: 1024
    output_size: 512